name: CI/CD Pipeline

on:
    push:
        branches: [ main ]

jobs:
    job_test:
        name: Executando job de teste
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Mensagem de execucao
          uses: echo "Ola mundo."
