name: CI/CD Pipeline

on:
    push:
        branches: [ main ]

jobs:
    build_and_test:
        name: Executando job de teste
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Mensagem de boas vindas.
          run: echo "Mensagem de boas vindas o caralho."
          
